language: python
matrix:
    include:
        - os: linux
          sudo: required
          python: "3.5"
          dist: trusty

        - os: linux
          sudo: required
          python: "3.6"
          dist: trusty

          - os: linux
          sudo: required
          python: "3.7"
          dist: trusty

          - os: linux
          sudo: required
          python: "3.8"
          dist: trusty

before_install:
  # Install miniconda3
  - .travis/installconda.sh
  - export PATH="$HOME/miniconda3/bin:$PATH"
  # Patch boto config (https://github.com/travis-ci/travis-ci/issues/7940)
  - export BOTO_CONFIG=/dev/null
install:
  # Create environments
  - conda env create -v -f environment-linux.yml
  - conda env create -v -f environment-linux-gpu.yml
script:
  - source activate deeplearning-labs && pip install pytest && pytest tests.py
