language: python
matrix:
    include:
        - os: linux
          python: "3.3"
          dist: trusty

        - os: linux
          python: "3.4"
          dist: trusty

        - os: linux
          python: "3.5"
          dist: trusty

        - os: linux
          python: "3.6"
          dist: trusty

        - os: osx
          language: generic
          python: "3.3"

        - os: osx
          language: generic
          python: "3.4"

        - os: osx
          language: generic
          python: "3.5"

        - os: osx
          language: generic
          python: "3.6"

before_install:
  # Install miniconda3
  - .travis/installconda.sh
install:
  # Create environments
  - conda env create -f deeplearning/environment-linux.yml 
script:
  # Deep Learning environment test
  - source activate deeplearning-labs && conda install nose && nosetests deeplearning

