name: deeplearning-labs
channels:
  - defaults
  - pytorch
dependencies:
  - keras=2.4.*
  - jupyter=1.0.*
  - matplotlib=3.3.*
  - pandas=1.1.*
  - pip=19.3.1
  - pytorch=1.4.*
  - scikit-learn=0.22.1
  - torchvision=0.5.*
  - pip:
    - pillow==5.3
    - tensorflow==2.3.*
    - transformers==2.5.1
