name: deeplearning-labs
channels:
  - defaults
  - pytorch
dependencies:
  - jupyter=1.0.*
  - matplotlib=3.3.*
  - pandas=1.1.*
  - pip=20.2.*
  - pytorch=1.4.*
  - scikit-learn=0.23.*
  - torchvision=0.5.*
  - pip:
    - keras==2.4.*
    - pillow==7.2.*
    - tensorflow==2.3.*
    - transformers==2.5.1
