name: deeplearning-labs-gpu
channels:
  - defaults
  - pytorch
dependencies:
  - cudatoolkit=10.1
  - cudnn=7.6.5
  - keras-gpu=2.4.*
  - jupyter=1.0.*
  - nb_conda=2.2.1
  - matplotlib=3.3.*
  - pandas=1.1.*
  - pip=19.3.1
  - pytorch=1.4.0
  - scikit-learn=0.22.1
  - torchvision=0.5.0
  - pip:
    - ipyplot==1.1.*
    - kaggle==1.5.*
    - tensorflow-gpu==2.3.*
    - transformers==2.5.1
