name: deeplearning-labs
channels:
  - defaults
  - pytorch
dependencies:
  - keras=2.4.*
  - jupyter=1.0.*
  - nb_conda=2.2.1
  - matplotlib=3.3.*
  - pandas=1.1.*
  - pip=19.3.1
  - pytorch=1.4.0
  - scikit-learn=0.22.1
  - torchvision=0.5.0
  - pip:
    - kaggle==1.5.*
    - tensorflow==2.3.*
    - transformers==2.5.1
