name: ensembles-labs
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - tornado<6
  - matplotlib=2.0.2
  - scikit-learn=0.19.1
  - pandas=0.23.0
  - graphviz=2.38
  - python-graphviz=0.8.4
  - seaborn=0.9.0
  - py-xgboost=0.80
  - ete3=3.1.1
  - scikit-optimize=0.5.2
